builds:
  - binary: playita
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
    flags:
      - -mod=vendor

release:
  prerelease: auto

checksum:
  name_template: "checksums-linux.txt"
