# .goreleaser.yaml
before:
  # Templates for the commands to be ran.
  hooks:
    - sudo apt install build-essential

builds:
  - binary: playita
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - # ID of resulting universal binary.
    id: playita

    ids:
      - build1
      - build2

    name_template: "{{.ProjectName}}_{{.Version}}"

    # Whether to remove the previous single-arch binaries from the artifact list.
    # If left as false, your end release might have both several macOS archives:
    # amd64, arm64 and all.
    replace: true

brews:
  - name: playita
    description: "Space repetition in the terminal"
    homepage: "https://github.com/carlosperez-dev/playita_cli"
    tap:
      owner: carlosperez-dev
      name: homebrew-playita
    commit_author:
      name: carlosperez-dev
      email: 67346082+carlosperez-dev@users.noreply.github.com

checksum:
  name_template: "checksums.txt"
