builds:
  - binary: playita
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
    flags:
      - -mod=vendor

brews:
  - name: playita
    description: "Space repetition in the terminal"
    homepage: "https://github.com/carlosperez-dev/playita_cli"
    tap:
      owner: carlosperez-dev
      name: homebrew-playita
    commit_author:
      name: carlosperez-dev
      email: 67346082+carlosperez-dev@users.noreply.github.com
    install: bin.install "playita"

release:
  prerelease: auto
