# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: goreleaser

on:
  push:

permissions:
  contents: write

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --skip-publish --config .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: playita-linux
          path: dist/playita*
  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --skip-publish --config .goreleaser-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: playita-darwin
          path: dist/playita*
  release:
    needs: [build-linux-binary, build-darwin-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: playita-linux
          path: ./playita-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: playita-darwin
          path: ./playita-build/darwin
      - name: Merge checksum file
        run: |
          cd ./playita-build
          cat ./darwin/checksums.txt >> checksums.txt
          cat ./linux/checksums.txt >> checksums.txt
          rm ./darwin/checksums.txt
          rm ./linux/checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config scripts/.goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
