# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.21
          dest: dist
          prefix: playita
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w
          trimpath: true

      # - name: Move artifacts
      #   run: |
      #     mv ./dist/linux/amd64/playita ./dist/playita_linux_amd64
      #     mv ./dist/darwin/amd64/playita ./dist/playita_darwin_amd64
      #     mv ./dist/windows/amd64/playita.exe ./dist/playita_windows_amd64.exe

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}

      # - name: Upload assets
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: playita
      #     path: ./dist/*

      # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
      # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
